name: Watchertower script execution

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 
    
    - name: Install Dependencies
      run: |
        pip install -r backend/requirements.txt
    
    - name: Execute Python Script
      run: python backend/app.py
    
    - name: Commit Results
      run: |
        git config --local user.email "bot@github.com"
        git config --local user.name "GitHub Action"
        git add output/data.json
        git commit -m "Updating JSON file"
        git push
